### ISSUE TITLE
Sheetness does not match original implementation

### ISSUE THREAD

**Issue by Besler** [ypauchard/ITK-KrcahSheetnessImageFilter#4]
The output sheetness image does not match the original implementation.

Original implementation available at https://github.com/mkrcah/bone-segmentation
Version compiled for ITKv4 available at https://github.com/Bonelab/bone-segmentation

I am using data `001-CT.nii` from the original repository.

Below is a comparison of a slice through a femur:
<img width="876" alt="screen shot 2017-08-01 at 13 58 53" src="https://user-images.githubusercontent.com/19190951/28844516-1871458c-76c2-11e7-9d09-546e33adf6f9.png">
Left is this implementation, right is Krcah.

Below is a histogram for the whole volume with 100 bins:
<img width="877" alt="screen shot 2017-08-01 at 13 59 42" src="https://user-images.githubusercontent.com/19190951/28844544-3765260c-76c2-11e7-89a7-ee4a6999cd0d.png">
Left is this implementation, right is Krcah.

**Comment by Besler** [comment]
The parameters in the published version do not match the parameters in the paper which do not match the parameters in this implementation. A tear down of parameters should be performed between this implementation and the other implementation.

**Comment by Besler** [comment]
The above image is wrong. The Krcah sheetness is scaled by 100 and stored as an integer (probably to reduce memory). Here they are scaled appropriately.

<img width="876" alt="screen shot 2017-08-01 at 14 09 49" src="https://user-images.githubusercontent.com/19190951/28844839-30c5ef38-76c3-11e7-9f6a-26b69f07c1f1.png">
Left is this implementation, right is Krcah.

From the comparison and the histogram, the Krcah implementation appears to have a much smoother sheetness measure for soft tissue.

**Comment by Besler** [comment]
Here is a teardown of the parameters:

| Sheetness Parameter | [Paper][1]  | [Original Implementation][2] | [This Implementation][3] |
| :-------------: | :-------------: | :-------------: | :-------------: |
| k  | 10  | 10  | 10 |
| s  | 1 | 1  | 1  |
| α | 0.5  | 0.5  | 0.5  |
| β | 0.5  | 0.5  | 0.5  |
| γ | 0.25  | 0.5  | 0.25  |
| Σ | {0.75, 1.0}  | {0.6, 0.8} | {0.75, 1.0}  |

In the [original implementation][2], there is an issue in the multiscale sheetness measure. It actually only takes the first scale passed to it (0.6 in this case). I wonder if Krcah released a later version of the software...

[1]: https://www.vision.ee.ethz.ch/en/publications/papers/proceedings/eth_biwi_00818.pdf
[2]: https://github.com/mkrcah/bone-segmentation
[3]: https://github.com/ypauchard/ITK-KrcahSheetnessImageFilter

**Comment by ypauchard** [comment]
Thanks, this is interesting. I'll try and have a look too.

Besides the parameters, it is very possible that the implementations for the sheetness image differ. Any help is appreciated!

**Comment by Besler** [comment]
Krcah implements everything after unsharp masking themselves. That is, using ITK to only implement a primitive form. They do use `vnl` for eigenvectors and values.

From Descoteaux _et al_,
<img src="https://user-images.githubusercontent.com/19190951/28891548-21537852-7788-11e7-81d1-e5ca21a941a0.png" width="250">

From Krcah _et al_,
<img src="https://user-images.githubusercontent.com/19190951/28891622-61eb1f8c-7788-11e7-8bd1-77c3f615f898.png" width="250">
> where _T_ denotes average trace of the Hessian at each image voxel.

If _T_ was just the trace of the Hessian at each pixel, then we can sum eigenvalues to get the trace:
<img src="https://user-images.githubusercontent.com/19190951/28892218-75240076-778a-11e7-845f-b35ec88998c3.png" width="250">

In the Krcah implementation, the _T_ is the average of all traces in the Hessian image.
<img src="https://user-images.githubusercontent.com/19190951/28892312-bcf849a2-778a-11e7-8310-71515f1b3491.png" width="250">

I see you use the average from a statistics filter now...

So that's not different!

**Comment by Besler** [comment]
Here are the images with the same Gamma and sheetness scales.

<img width="873" alt="screen shot 2017-08-02 at 15 55 12" src="https://user-images.githubusercontent.com/19190951/28896788-1e6ad104-779b-11e7-9019-fd9a786c8275.png">
Left is Krcah, right is this implementation.

The Krcah method is still much smoother outside the body and has an improved response around the femoral head.

**Comment by Besler** [comment]
Okay, now I think I found the difference. The sheetness measure in the Krcah implementation is not the same as described in the paper. 

The sheetness measure in the implementation is this:
<img src="https://user-images.githubusercontent.com/19190951/28898893-6d595830-77a5-11e7-8ee1-e0e10e2aaa49.png" width="700">

Where 
<img src="https://user-images.githubusercontent.com/19190951/28899131-b1737496-77a6-11e7-8029-79952557abb5.png" width="200">

You can see this in the [original code](https://github.com/mkrcah/bone-segmentation/blame/eb4e02b0a5f6f36348ffcdfbd1e9a2a4e996d2bd/src/proposed-method/src/filters/SheetnessMeasure.hpp#L265).

γ is actually set to 0.25 taking into account this change.

Seeing as the parameters in the Krcah implementation do not match the parameters in the original paper, I am going to venture a guess that the paper and the implementation we have are not the same. Who knows if this is accidental or not.

Intuitively, I think this would explain the difference in images. R_blob would be large if the Hessian of the image was very constant. If R_blob is large, the sheetness measure is driven down.

**Comment by Besler** [comment]
Making the above change I get this:

<img width="875" alt="screen shot 2017-08-02 at 17 34 15" src="https://user-images.githubusercontent.com/19190951/28899528-d7fe3ab8-77a8-11e7-96dc-d3a8cc6a9388.png">

I'm not happy with this result. Given the number of errors and mismatch between the Krcah implementation and the paper I am thinking it might not be worth chasing.

**Comment by Besler** [comment]
In this implementation, Hessian is computed using [`itk::HessianRecursiveGaussianImageFilter`](https://itk.org/Doxygen/html/classitk_1_1HessianRecursiveGaussianImageFilter.html). This class:
> Computes the Hessian matrix of an image by convolution with the Second and Cross derivatives of a Gaussian.

 In the Krcah implementation, they smooth the image with `itk::SmoothingRecursiveGaussianImageFilter` and calculate the matrix elements of the Hessian by central difference about the current pixel.

**Comment by Besler** [comment]
Also, their α, β, and γ are really multiplied by sqrt(2) in the Krcah implementation as compared with the paper.

I run with the undated sheetness parameters (α, β, γ) and with the _blob_ inclusion and I get this:
<img width="878" alt="screen shot 2017-08-02 at 18 13 29" src="https://user-images.githubusercontent.com/19190951/28900448-8112194e-77ae-11e7-9fda-3e89d8719f5c.png">

This is getting to me @ypauchard... Maybe open science really matters? :p

**Comment by Besler** [comment]
Another implementation nuance. They do not compute the trace of the Hessian matrix. They compute the sum of the absolute value of the eigenvalues (see [here](https://github.com/mkrcah/bone-segmentation/blame/eb4e02b0a5f6f36348ffcdfbd1e9a2a4e996d2bd/src/proposed-method/src/filters/SheetnessMeasure.hpp#L244)).

I do that and I get:
<img width="877" alt="screen shot 2017-08-02 at 18 55 55" src="https://user-images.githubusercontent.com/19190951/28901283-46d5dd64-77b4-11e7-8878-0986c0e0bff3.png">

**Comment by Besler** [comment]
Another trick! gamma^2 = 0.25!

Implementing that we get:
<img width="876" alt="screen shot 2017-08-02 at 19 03 50" src="https://user-images.githubusercontent.com/19190951/28901447-676fa64e-77b5-11e7-8c50-61b093a5b905.png">

**Comment by Besler** [comment]
Now with setting gamma^2 = 0.5.

<img width="872" alt="screen shot 2017-08-02 at 19 09 47" src="https://user-images.githubusercontent.com/19190951/28901557-3bb4b606-77b6-11e7-8444-0c7aeb1d38c1.png">

**Comment by Besler** [comment]
This is with removing the _blob_ exponential:
<img width="879" alt="screen shot 2017-08-02 at 19 12 48" src="https://user-images.githubusercontent.com/19190951/28901620-b99b2154-77b6-11e7-8f75-8f98733a7b90.png">

I am going to stop here. Summary of the Krcah implementation:

- _T_ is the average of the sum of the absolute value of the eigenvalues, not the average trace.
- The Hessian was computed different (and the central difference formula is wrong).
- Many parameters are incorrect in the paper.
- It is unclear if the Krcah implementation available online matches the implementation in the paper.

Either way, one will have to play with the sheetness filter to determine an appropriate set of parameters given the implementation differences.

**Comment by ypauchard** [comment]
We could:
1. adapt this implementation to match the original code
2. Leave as is, do nothing
3. Leave as is, and look at 'sheetness for graph cut' from a new perspective

I favour 2. or 3.

If it were 3., we could start wtih:
1. rename the github repo to 'SheetnessGraphCut'
2. refactor the code to:
* Have unsharp masking as a pre-processing step outside KrcahSheetnessFeatureGenerator.hxx
* Do multi-level as proposed by the pull request
* add Descoteaux sheetness as implemented in  [itktubeSheetnessMeasureImageFilter.hxx]( https://github.com/KitwareMedical/ITKTubeTK/blob/4aafa30cc9ebe134fa0aed93c8711f47ceaeaeca/Base/Filtering/itktubeSheetnessMeasureImageFilter.hxx) rather than the Functor version in ITK
* Convert  KrcahSheetness from functor to above (optional).

I think it is worth investigating Descoteaux's original measure.

Descoteaux in [itktubeSheetnessMeasureImageFilter.hxx]( https://github.com/KitwareMedical/ITKTubeTK/blob/4aafa30cc9ebe134fa0aed93c8711f47ceaeaeca/Base/Filtering/itktubeSheetnessMeasureImageFilter.hxx) is implemented with iterators and an ImageToImage filter rather than functors. I like this better. Also, the input is the output of the itkHessianRecursiveGaussianImageFilter, and putting things together results in:
```
filterHessian->SetInput( inputImage );
filterHessian->SetSigma( 0.5 );
filterSheetness->SetInput( filterHessian->GetOutput() );

filterSheetness->Update();
```
see [itktubeSheetnessMeasureImageFilterTest.cxx](https://github.com/KitwareMedical/ITKTubeTK/blob/d2525da27613ac5c3c7746e7bdbcf13124def524/Base/Filtering/Testing/itktubeSheetnessMeasureImageFilterTest.cxx)

**Comment by Besler** [comment]
I was thinking about it last night. Krcah was trying to get _negative_ sheetness between joints. This really increases contrast. Descoteaux gets a zero between joints.

**Comment by Besler** [comment]
If we go sheetness with GraphCut (3), we to reimplement the GraphCut. I don't like how [daviddoria](https://github.com/Besler/ImageGraphCutSegmentation) setup his code... Maybe that's the ITK way. I would rather cannibalize Celli119's work. The issues is that most ITK methods are 'locked down'. I like iterators more than functors as well.

Sheetness is a general concept. There should be an abstract class that implements Gauss -> Hess -> Eigen -> virtual prototyped function -> max response. Similarly, GraphCut is a general concept. There should be an abstract class where you set the regional/data and boundary/smooth terms by inheritance and implementation.

If we're going to move forward, I would break apart the GraphCut work in MITK-GEM and this work into two repositories: `ITK-SheetnessMeasure` and `ITK-GraphCut`

- There is a base abstract class `itkSheetnessMeasure`.
  - This class implements Gauss -> Hess -> Eigen -> call virtual function -> multiscale (but not unsharp).
  - We can implement all sheetness measures but the Krcah method (because they scale their sheetness value globally - *bad*)
- There is a base abstract class `itkGraphCut`.
  - This class implements interfacing with kolmogrov/boykov/GridCut. The trick is to have a build-time dependance.
  - We inherit from this class and implement specific regional/boundary terms

Benefit of implementing each of these classes separately:

- Use `git submodule` to get the code into MITK-GEM.
- Development can happen independently from MITK-GEM. Ideally, these class would be put into ITK as modules.
- We can use the code elsewhere.

**Comment by Besler** [comment]
@ypauchard, do you think your MITK-GEM friends will bite?

**Comment by Besler** [comment]
@ypauchard, I will be away this weekend so we can talk Tuesday. If we can break out the multi label GraphCut stuff into a separate ITK package that would be ideal. It's too 'locked down'. The data/regional and smooth/boundary terms should be exposed.
